### ISSUE TITLE
ClusterAutoscaler conflicts when two clusters are running

### ISSUE THREAD

**Issue by Phylu** [kubernetes-incubator/kube-aws#816]
I start two clusters using kube-aws prefix-clust-production and prefix-clust-development. The clusters look the same except that production/development as a suffix differentiate all resources.

When I first activated the clusterAutoscaler in the first cluster, everything worked fine. If - however - I activate the clusterAutoscaler in the second cluster, scaling up fails. The following output is from the clusterAutoscaler from the DEVELOPMENT cluster:
```
I0802 22:38:03.212729       1 aws_manager.go:190] Regenerating ASG information for prefix-clust-production-Nppublic1production-17GWAKZUGHW9J-Workers-AH8MJS9C656N
E0802 22:38:03.298790       1 static_autoscaler.go:219] Failed to scale up: failed to find template node for node group prefix-clust-production-Npprivate1production-1SOZPPQFRI7YR-Workers-1BW32ALXP9NEC
W0802 22:38:03.298931       1 clusterstate.go:237] Failed to find readiness information for prefix-clust-production-Npprivate1production-1SOZPPQFRI7YR-Workers-1BW32ALXP9NEC
```

Here, the development clusterAutoscaler somehow sees the nodes from the production cluster and fails, as it cannot access them.

**Comment by mumoshu** [comment]
@Phylu Hi and sorry for the inconvenience 😢 

Probably you're using kube-aws v0.9.7, right?

The bug is introduced by me and the fix didn't made in the default version of CA for kube-aws v0.9.7.
Anyways, it is fixed since CA v0.6.0. You explicitly override the CA image used by kube-aws like the below in cluster.yaml:

```
clusterAutoscalerImage:
  repo: gcr.io/google_containers/cluster-autoscaler
  tag: v0.6.0
```

Otherwise, you can just `kubectl edit deployment cluster-autoscaler` and update `image` accordingly for a temporary fix.

Would you mind trying one of two workarounds and reporting back if it works?

**Comment by Phylu** [comment]
Hi @mumoshu 

Yes, I am using kube-aws 0.9.7. I manually changed the deployment of the cluster-autoscaler accordingly: `image: gcr.io/google_containers/cluster-autoscaler:v0.6.0'

Unfortunately, this does not solve the issue:
```
I0803 00:29:43.179790       1 main.go:225] Cluster Autoscaler 0.6.0
...
E0803 00:30:12.385819       1 static_autoscaler.go:245] Failed to scale up: failed to find template node for node group cs-clust-production-Npprivate1-1SOZPPQFRI7YR-Workers-1BW32ALXP9NEC
W0803 00:30:12.386286       1 clusterstate.go:237] Failed to find readiness information for cs-clust-production-Npprivate1-1SOZPPQFRI7YR-Workers-1BW32ALXP9NEC
```

**Comment by mumoshu** [comment]
@Phylu Oops! Would you mind modifying the `--nodes-group-discovery` option like:

```
- --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/YOUR_CLUSTER_NAME
```

This way, CA utilizes the cluster name tag to differentiate ASGs from different k8s clusters.

Please replace `YOUR_CLUSTER_NAME` with your `clusterName` in cluster.yaml.

**Comment by mumoshu** [comment]
FYI the fix on kube-aws side is in #743 and it will be included in kube-aws v0.9.8-rc.1(unreleased yet).

**Comment by Phylu** [comment]
Perfect! Thanks a lot. 👍 
That works nicely.
